services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Bind mount for syncing local changes
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
